// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwnsfbpjlhnoaskcxvat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3bnNmYnBqbGhub2Fza2N4dmF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDgyMTgsImV4cCI6MjA3MDU4NDIxOH0.eY7wqyZGSLA5_w14uEWkJZzOzM2M8PFw1cF3wJIekiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});